"""
This type stub file was generated by pyright.
"""

from ..debugging import bacpypes_debugging
from ..comm import Client, Server
from ..pdu import LocalStation, PDU

"""
Link Layer Module

Classes in this module extend the BVLLServiceAccessPoint subclasses with
additional components necessary to send packets down to a virtual network.

The clients of instances of these object (next up the stack) is a NetworkAdapter
instance which references a NetworkServiceAccessPoint.
"""
_debug = ...
_log = ...
@bacpypes_debugging
class VirtualLinkLayer(Client[PDU], Server[PDU]):
    """
    Create a link layer mini-stack ...
    """
    def __init__(self, local_address: LocalStation, network_interface_name: str, **kwargs) -> None:
        ...
    
    async def indication(self, pdu: PDU) -> None:
        ...
    
    async def confirmation(self, pdu: PDU) -> None:
        ...
    
    def close(self): # -> None:
        ...
    


