"""
This type stub file was generated by pyright.
"""

import asyncio
from typing import Callable, Optional, TYPE_CHECKING, Union
from .debugging import bacpypes_debugging
from .comm import Client

"""
Console
"""
_debug = ...
_log = ...
ConsolePDU = Union[int, str, None]
if TYPE_CHECKING:
    ConsoleQueue = asyncio.Queue[ConsolePDU]
else:
    ...
@bacpypes_debugging
class Console(Client[ConsolePDU]):
    """
    A Console object sits at the top of a stack reading input from the
    interactive console (a.k.a. terminal), pipe input, or file input, and sends
    each string down the stack.  Strings coming up the stack are written to
    stdout.

    The 'fini' event is set when there is no more input, a.k.a. EOF.
    """
    _debug: Callable[..., None]
    fini: asyncio.Event
    exit_status: int
    def __init__(self, prompt: Optional[str] = ..., history_file: Optional[str] = ..., cid: Optional[str] = ...) -> None:
        ...
    
    def preloop(self) -> None:
        """Initialization before prompting user for commands."""
        ...
    
    def postloop(self) -> None:
        """Take care of any unfinished business."""
        ...
    
    def kill(self) -> None:
        """
        Send a SystemExit exception to the console input thread.
        """
        ...
    
    def console_input(self, fini: asyncio.Event, prompt: str) -> None:
        """
        This method uses the input() blocking function to read a line of text
        from stdin and supports readline for interactive sessions.  It runs in
        its own thread to keep the main event loop alive.
        """
        ...
    
    async def console_supervisor(self) -> None:
        """
        This supervisory function calls preloop to load up the history, starts
        the console thread and wait for it to complete, sends an EOF message
        down the stack, saves the history, and sets the fini event flag.
        """
        ...
    
    async def confirmation(self, pdu: ConsolePDU) -> None:
        """
        Upstream messages are strings to send to stdout, or integer status
        codes to shutdown the console down.  It is the responsibility of the
        main() function to call sys.exit() with the exit status code when it is
        appropriate.
        """
        ...
    


