"""
This type stub file was generated by pyright.
"""

from typing import Any as _Any, Callable, Dict, Optional, Tuple, Union
from .debugging import bacpypes_debugging
from .primitivedata import (
    BitString,
    Boolean,
    CharacterString,
    Date,
    Double,
    Integer,
    ObjectIdentifier,
    ObjectType,
    OctetString,
    Real,
    Time,
    Unsigned,
    Unsigned16,
    Unsigned8,
)
from .constructeddata import AnyAtomic, ArrayOf, ListOf, Sequence, SequenceMetaclass
from .basetypes import (
    AccessCredentialDisable,
    AccessCredentialDisableReason,
    AccessEvent,
    AccessPassbackMode,
    AccessRule,
    AccessThreatLevel,
    AccessUserType,
    AccessZoneOccupancyState,
    AccumulatorRecord,
    Action,
    ActionList,
    AddressBinding,
    AssignedAccessRights,
    AssignedLandingCalls,
    AuditLevel,
    AuditLogRecord,
    AuditOperationFlags,
    AuthenticationFactor,
    AuthenticationFactorFormat,
    AuthenticationPolicy,
    AuthenticationStatus,
    AuthorizationException,
    AuthorizationMode,
    BDTEntry,
    BackupState,
    BinaryLightingPV,
    BinaryPV,
    COVMultipleSubscription,
    COVSubscription,
    CalendarEntry,
    ChannelValue,
    ClientCOV,
    CredentialAuthenticationFactor,
    DailySchedule,
    DateRange,
    DateTime,
    Destination,
    DeviceObjectPropertyReference,
    DeviceObjectReference,
    DeviceStatus,
    DoorAlarmState,
    DoorSecuredStatus,
    DoorStatus,
    DoorValue,
    EngineeringUnits,
    EscalatorFault,
    EscalatorMode,
    EscalatorOperationDirection,
    EventLogRecord,
    EventNotificationSubscription,
    EventParameter,
    EventState,
    EventTransitionBits,
    EventType,
    FDTEntry,
    FaultParameter,
    FaultType,
    FileAccessMethod,
    HostNPort,
    IPMode,
    IPv4OctetString,
    IPv6OctetString,
    LandingCallStatus,
    LandingDoorStatus,
    LifeSafetyMode,
    LifeSafetyOperation,
    LifeSafetyState,
    LiftCarCallList,
    LiftCarDirection,
    LiftCarDoorCommand,
    LiftCarDriveStatus,
    LiftCarMode,
    LiftFault,
    LiftGroupMode,
    LightingCommand,
    LightingInProgress,
    LightingTransition,
    LimitEnable,
    LockStatus,
    LogMultipleRecord,
    LogRecord,
    LoggingType,
    MACAddress,
    Maintenance,
    NameValue,
    NameValueCollection,
    NetworkNumberQuality,
    NetworkPortCommand,
    NetworkSecurityPolicy,
    NetworkType,
    NodeType,
    NotifyType,
    ObjectPropertyReference,
    ObjectSelector,
    ObjectTypesSupported,
    OptionalBinaryPV,
    OptionalCharacterString,
    OptionalPriorityFilter,
    OptionalReal,
    OptionalUnsigned,
    Polarity,
    PortPermission,
    Prescale,
    PriorityFilter,
    PriorityValue,
    ProcessIdSelection,
    ProgramError,
    ProgramRequest,
    ProgramState,
    PropertyAccessResult,
    PropertyIdentifier,
    ProtocolLevel,
    ReadAccessResult,
    ReadAccessSpecification,
    Recipient,
    Relationship,
    Reliability,
    RestartReason,
    RouterEntry,
    Scale,
    SecurityKeySet,
    SecurityLevel,
    Segmentation,
    ServicesSupported,
    SessionKey,
    SetpointReference,
    ShedLevel,
    ShedState,
    SilencedState,
    SpecialEvent,
    StageLimitValue,
    StatusFlags,
    TimeStamp,
    TimerState,
    TimerStateChangeValue,
    TimerTransition,
    VMACEntry,
    VTClass,
    VTSession,
    ValueSource,
    WriteStatus,
)

"""
Object
"""
_debug = ...
_log = ...

class ObjectMetaclass(SequenceMetaclass):
    """
    Amazing documentation here.
    """

    _debug: Callable[..., None]
    def __new__(
        cls: _Any,
        clsname: str,
        superclasses: Tuple[type, ...],
        attributedict: Dict[str, _Any],
    ) -> ObjectMetaclass: ...

class Object(Sequence, metaclass=ObjectMetaclass):
    """
    Amazing documentation here.
    """

    _debug: Callable[..., None]
    _vendor_id: int
    _object_identifier_class = ObjectIdentifier
    _property_identifier_class = PropertyIdentifier
    _app: _Any
    _required = ...
    objectIdentifier: ObjectIdentifier
    objectName: CharacterString(_min_length=1)
    objectType: ObjectType
    description: CharacterString
    propertyList: ArrayOf(PropertyIdentifier)
    auditLevel: AuditLevel
    auditableOperations: AuditOperationFlags
    tags: ArrayOf(NameValue)
    profileLocation: CharacterString
    profileName: CharacterString
    def __init__(
        self, init_dict: Optional[Dict[str, _Any]] = ..., **kwargs: _Any
    ) -> None: ...
    @classmethod
    def get_property_type(cls, attr: Union[int, str, PropertyIdentifier]) -> _Any:
        """Given a property identifier, return its type, its associated class."""
        ...

    async def read_property(
        self, attr: Union[int, str], index: Optional[int] = ...
    ) -> _Any: ...
    async def write_property(
        self,
        attr: Union[int, str],
        value: _Any,
        index: Optional[int] = ...,
        priority: Optional[int] = ...,
    ) -> None: ...

_vendor_id = ...

class AccessCredentialObject(Object):
    _required = ...
    objectType = ...
    globalIdentifier: Unsigned
    statusFlags: StatusFlags
    reliability: Reliability
    credentialStatus: BinaryPV
    reasonForDisable: ListOf(AccessCredentialDisableReason)
    authenticationFactors: ArrayOf(CredentialAuthenticationFactor)
    activationTime: DateTime
    expirationTime: DateTime
    credentialDisable: AccessCredentialDisable
    daysRemaining: Integer
    usesRemaining: Integer
    absenteeLimit: Unsigned
    belongsTo: DeviceObjectReference
    assignedAccessRights: ArrayOf(AssignedAccessRights)
    lastAccessPoint: DeviceObjectReference
    lastAccessEvent: AccessEvent
    lastUseTime: DateTime
    traceFlag: Boolean
    threatAuthority: AccessThreatLevel
    extendedTimeEnable: Boolean
    authorizationExemptions: ListOf(AuthorizationException)
    reliabilityEvaluationInhibit: Boolean

class AccessDoorObject(Object):
    _required = ...
    objectType = ...
    presentValue: DoorValue
    statusFlags: StatusFlags
    eventState: EventState
    reliability: Reliability
    outOfService: Boolean
    priorityArray: ArrayOf(PriorityValue, _length=16)
    relinquishDefault: DoorValue
    doorStatus: DoorStatus
    lockStatus: LockStatus
    securedStatus: DoorSecuredStatus
    doorMembers: ArrayOf(DeviceObjectReference)
    doorPulseTime: Unsigned
    doorExtendedPulseTime: Unsigned
    doorUnlockDelayTime: Unsigned
    doorOpenTooLongTime: Unsigned
    doorAlarmState: DoorAlarmState
    maskedAlarmValues: ListOf(DoorAlarmState)
    maintenanceRequired: Maintenance
    timeDelay: Unsigned
    notificationClass: Unsigned
    alarmValues: ListOf(DoorAlarmState)
    faultValues: ListOf(DoorAlarmState)
    eventEnable: EventTransitionBits
    ackedTransitions: EventTransitionBits
    notifyType: NotifyType
    eventTimeStamps: ArrayOf(TimeStamp, _length=3)
    eventMessageTexts: ArrayOf(CharacterString, _length=3)
    eventMessageTextsConfig: ArrayOf(CharacterString, _length=3)
    eventDetectionEnable: Boolean
    eventAlgorithmInhibitRef: ObjectPropertyReference
    eventAlgorithmInhibit: Boolean
    timeDelayNormal: Unsigned
    reliabilityEvaluationInhibit: Boolean
    currentCommandPriority: OptionalUnsigned
    valueSource: ValueSource
    valueSourceArray: ArrayOf(ValueSource, _length=16)
    lastCommandTime: TimeStamp
    commandTimeArray: ArrayOf(TimeStamp, _length=16)
    auditPriorityFilter: OptionalPriorityFilter

class AccessPointObject(Object):
    _required = ...
    objectType = ...
    statusFlags: StatusFlags
    eventState: EventState
    reliability: Reliability
    outOfService: Boolean
    authenticationStatus: AuthenticationStatus
    activeAuthenticationPolicy: Unsigned
    numberOfAuthenticationPolicies: Unsigned
    authenticationPolicyList: ArrayOf(AuthenticationPolicy)
    authenticationPolicyNames: ArrayOf(CharacterString)
    authorizationMode: AuthorizationMode
    verificationTime: Unsigned
    lockout: Boolean
    lockoutRelinquishTime: Unsigned
    failedAttempts: Unsigned
    failedAttemptEvents: ListOf(AccessEvent)
    maxFailedAttempts: Unsigned
    failedAttemptsTime: Unsigned
    threatLevel: AccessThreatLevel
    occupancyUpperLimitEnforced: Boolean
    occupancyLowerLimitEnforced: Boolean
    occupancyCountAdjust: Boolean
    accompanimentTime: Unsigned
    accessEvent: AccessEvent
    accessEventTag: Unsigned
    accessEventTime: TimeStamp
    accessEventCredential: DeviceObjectReference
    accessEventAuthenticationFactor: AuthenticationFactor
    accessDoors: ArrayOf(DeviceObjectReference)
    priorityForWriting: Unsigned
    musterPoint: Boolean
    zoneTo: DeviceObjectReference
    zoneFrom: DeviceObjectReference
    notificationClass: Unsigned
    transactionNotificationClass: Unsigned
    accessAlarmEvents: ListOf(AccessEvent)
    accessTransactionEvents: ListOf(AccessEvent)
    eventEnable: EventTransitionBits
    ackedTransitions: EventTransitionBits
    notifyType: NotifyType
    eventTimeStamps: ArrayOf(TimeStamp, _length=3)
    eventMessageTexts: ArrayOf(CharacterString, _length=3)
    eventMessageTextsConfig: ArrayOf(CharacterString, _length=3)
    eventDetectionEnable: Boolean
    eventAlgorithmInhibitRef: ObjectPropertyReference
    eventAlgorithmInhibit: Boolean
    reliabilityEvaluationInhibit: Boolean

class AccessRightsObject(Object):
    _required = ...
    objectType = ...
    globalIdentifier: Unsigned
    statusFlags: StatusFlags
    reliability: Reliability
    enable: Boolean
    negativeAccessRules: ArrayOf(AccessRule)
    positiveAccessRules: ArrayOf(AccessRule)
    accompaniment: DeviceObjectReference
    reliabilityEvaluationInhibit: Boolean

class AccessUserObject(Object):
    _required = ...
    objectType = ...
    globalIdentifier: Unsigned
    statusFlags: StatusFlags
    reliability: Reliability
    userType: AccessUserType
    userName: CharacterString
    userExternalIdentifier: CharacterString
    userInformationReference: CharacterString
    members: ListOf(DeviceObjectReference)
    memberOf: ListOf(DeviceObjectReference)
    credentials: ListOf(DeviceObjectReference)
    reliabilityEvaluationInhibit: Boolean

class AccessZoneObject(Object):
    _required = ...
    objectType = ...
    globalIdentifier: Unsigned
    occupancyState: AccessZoneOccupancyState
    statusFlags: StatusFlags
    eventState: EventState
    reliability: Reliability
    outOfService: Boolean
    occupancyCount: Unsigned
    occupancyCountEnable: Boolean
    adjustValue: Integer
    occupancyUpperLimit: Unsigned
    occupancyLowerLimit: Unsigned
    credentialsInZone: ListOf(DeviceObjectReference)
    lastCredentialAdded: DeviceObjectReference
    lastCredentialAddedTime: DateTime
    lastCredentialRemoved: DeviceObjectReference
    lastCredentialRemovedTime: DateTime
    passbackMode: AccessPassbackMode
    passbackTimeout: Unsigned
    entryPoints: ListOf(DeviceObjectReference)
    exitPoints: ListOf(DeviceObjectReference)
    timeDelay: Unsigned
    notificationClass: Unsigned
    alarmValues: ListOf(AccessZoneOccupancyState)
    eventEnable: EventTransitionBits
    ackedTransitions: EventTransitionBits
    notifyType: NotifyType
    eventTimeStamps: ArrayOf(TimeStamp, _length=3)
    eventMessageTexts: ArrayOf(CharacterString, _length=3)
    eventMessageTextsConfig: ArrayOf(CharacterString, _length=3)
    eventDetectionEnable: Boolean
    eventAlgorithmInhibitRef: ObjectPropertyReference
    eventAlgorithmInhibit: Boolean
    timeDelayNormal: Unsigned
    reliabilityEvaluationInhibit: Boolean

class AccumulatorObject(Object):
    _required = ...
    objectType = ...
    presentValue: Unsigned
    deviceType: CharacterString
    statusFlags: StatusFlags
    eventState: EventState
    reliability: Reliability
    outOfService: Boolean
    scale: Scale
    units: EngineeringUnits
    prescale: Prescale
    maxPresValue: Unsigned
    valueChangeTime: DateTime
    valueBeforeChange: Unsigned
    valueSet: Unsigned
    loggingRecord: AccumulatorRecord
    loggingObject: ObjectIdentifier
    pulseRate: Unsigned
    highLimit: Unsigned
    lowLimit: Unsigned
    limitMonitoringInterval: Unsigned
    notificationClass: Unsigned
    timeDelay: Unsigned
    limitEnable: LimitEnable
    eventEnable: EventTransitionBits
    ackedTransitions: EventTransitionBits
    notifyType: NotifyType
    eventTimeStamps: ArrayOf(TimeStamp, _length=3)
    eventMessageTexts: ArrayOf(CharacterString, _length=3)
    eventMessageTextsConfig: ArrayOf(CharacterString, _length=3)
    eventDetectionEnable: Boolean
    eventAlgorithmInhibitRef: ObjectPropertyReference
    eventAlgorithmInhibit: Boolean
    timeDelayNormal: Unsigned
    reliabilityEvaluationInhibit: Boolean
    faultHighLimit: Unsigned
    faultLowLimit: Unsigned

class AlertEnrollmentObject(Object):
    _required = ...
    objectType = ...
    presentValue: ObjectIdentifier
    eventState: EventState
    eventDetectionEnable: Boolean
    notificationClass: Unsigned
    eventEnable: EventTransitionBits
    ackedTransitions: EventTransitionBits
    notifyType: NotifyType
    eventTimeStamps: ArrayOf(TimeStamp, _length=3)
    eventMessageTexts: ArrayOf(CharacterString, _length=3)
    eventMessageTextsConfig: ArrayOf(CharacterString, _length=3)
    eventAlgorithmInhibitRef: ObjectPropertyReference
    eventAlgorithmInhibit: Boolean

class AnalogInputObject(Object):
    _required = ...
    objectType = ...
    presentValue: Real
    deviceType: CharacterString
    statusFlags: StatusFlags
    eventState: EventState
    reliability: Reliability
    outOfService: Boolean
    updateInterval: Unsigned
    units: EngineeringUnits
    minPresValue: Real
    maxPresValue: Real
    resolution: Real
    covIncrement: Real
    timeDelay: Unsigned
    notificationClass: Unsigned
    highLimit: Real
    lowLimit: Real
    deadband: Real
    limitEnable: LimitEnable
    eventEnable: EventTransitionBits
    ackedTransitions: EventTransitionBits
    notifyType: NotifyType
    eventTimeStamps: ArrayOf(TimeStamp, _length=3)
    eventMessageTexts: ArrayOf(CharacterString, _length=3)
    eventMessageTextsConfig: ArrayOf(CharacterString, _length=3)
    eventDetectionEnable: Boolean
    eventAlgorithmInhibitRef: ObjectPropertyReference
    eventAlgorithmInhibit: Boolean
    timeDelayNormal: Unsigned
    reliabilityEvaluationInhibit: Boolean
    interfaceValue: OptionalReal
    faultHighLimit: Real
    faultLowLimit: Real

class AnalogOutputObject(Object):
    _required = ...
    objectType = ...
    presentValue: Real
    deviceType: CharacterString
    statusFlags: StatusFlags
    eventState: EventState
    reliability: Reliability
    outOfService: Boolean
    units: EngineeringUnits
    minPresValue: Real
    maxPresValue: Real
    resolution: Real
    priorityArray: ArrayOf(PriorityValue, _length=16)
    relinquishDefault: Real
    covIncrement: Real
    timeDelay: Unsigned
    notificationClass: Unsigned
    highLimit: Real
    lowLimit: Real
    deadband: Real
    limitEnable: LimitEnable
    eventEnable: EventTransitionBits
    ackedTransitions: EventTransitionBits
    notifyType: NotifyType
    eventTimeStamps: ArrayOf(TimeStamp, _length=3)
    eventMessageTexts: ArrayOf(CharacterString, _length=3)
    eventMessageTextsConfig: ArrayOf(CharacterString, _length=3)
    eventDetectionEnable: Boolean
    eventAlgorithmInhibitRef: ObjectPropertyReference
    eventAlgorithmInhibit: Boolean
    timeDelayNormal: Unsigned
    reliabilityEvaluationInhibit: Boolean
    interfaceValue: OptionalReal
    currentCommandPriority: OptionalUnsigned
    valueSource: ValueSource
    valueSourceArray: ArrayOf(ValueSource, _length=16)
    lastCommandTime: TimeStamp
    commandTimeArray: ArrayOf(TimeStamp, _length=16)
    auditPriorityFilter: OptionalPriorityFilter

class AnalogValueObject(Object):
    _required = ...
    objectType = ...
    presentValue: Real
    statusFlags: StatusFlags
    eventState: EventState
    reliability: Reliability
    outOfService: Boolean
    units: EngineeringUnits
    minPresValue: Real
    maxPresValue: Real
    resolution: Real
    priorityArray: ArrayOf(PriorityValue, _length=16)
    relinquishDefault: Real
    covIncrement: Real
    timeDelay: Unsigned
    notificationClass: Unsigned
    highLimit: Real
    lowLimit: Real
    deadband: Real
    limitEnable: LimitEnable
    eventEnable: EventTransitionBits
    ackedTransitions: EventTransitionBits
    notifyType: NotifyType
    eventTimeStamps: ArrayOf(TimeStamp, _length=3)
    eventMessageTexts: ArrayOf(CharacterString, _length=3)
    eventMessageTextsConfig: ArrayOf(CharacterString, _length=3)
    eventDetectionEnable: Boolean
    eventAlgorithmInhibitRef: ObjectPropertyReference
    eventAlgorithmInhibit: Boolean
    timeDelayNormal: Unsigned
    reliabilityEvaluationInhibit: Boolean
    faultHighLimit: Real
    faultLowLimit: Real
    currentCommandPriority: OptionalUnsigned
    valueSource: ValueSource
    valueSourceArray: ArrayOf(ValueSource, _length=16)
    lastCommandTime: TimeStamp
    commandTimeArray: ArrayOf(TimeStamp, _length=16)
    auditPriorityFilter: OptionalPriorityFilter

class AuditLogObject(Object):
    _required = ...
    objectType = ...
    statusFlags: StatusFlags
    eventState: EventState
    reliability: Reliability
    enable: Boolean
    bufferSize: Unsigned
    logBuffer: ListOf(AuditLogRecord)
    recordCount: Unsigned
    totalRecordCount: Unsigned
    memberOf: DeviceObjectReference
    deleteOnForward: Boolean
    issueConfirmedNotifications: Boolean
    eventDetectionEnable: Boolean
    notificationClass: Unsigned
    eventEnable: EventTransitionBits
    ackedTransitions: EventTransitionBits
    notifyType: NotifyType
    eventTimeStamps: ArrayOf(TimeStamp, _length=3)
    eventMessageTexts: ArrayOf(CharacterString, _length=3)
    eventMessageTextsConfig: ArrayOf(CharacterString, _length=3)
    reliabilityEvaluationInhibit: Boolean

class AuditReporterObject(Object):
    _required = ...
    objectType = ...
    statusFlags: StatusFlags
    reliability: Reliability
    eventState: EventState
    auditLevel: AuditLevel
    auditSourceReporter: Boolean
    auditableOperations: AuditOperationFlags
    auditPriorityFilter: PriorityFilter
    issueConfirmedNotifications: Boolean
    monitoredObjects: ArrayOf(ObjectSelector)
    maximumSendDelay: Unsigned
    sendNow: Boolean
    eventDetectionEnable: Boolean
    notificationClass: Unsigned
    eventEnable: EventTransitionBits
    ackedTransitions: EventTransitionBits
    notifyType: NotifyType
    eventTimeStamps: ArrayOf(TimeStamp, _length=3)
    eventMessageTexts: ArrayOf(CharacterString, _length=3)
    eventMessageTextsConfig: ArrayOf(CharacterString, _length=3)
    reliabilityEvaluationInhibit: Boolean

class AveragingObject(Object):
    _required = ...
    objectType = ...
    minimumValue: Real
    minimumValueTimestamp: DateTime
    averageValue: Real
    varianceValue: Real
    maximumValue: Real
    maximumValueTimestamp: DateTime
    attemptedSamples: Unsigned
    validSamples: Unsigned
    objectPropertyReference: DeviceObjectPropertyReference
    windowInterval: Unsigned
    windowSamples: Unsigned

class BinaryInputObject(Object):
    _required = ...
    objectType = ...
    presentValue: BinaryPV
    deviceType: CharacterString
    statusFlags: StatusFlags
    eventState: EventState
    reliability: Reliability
    outOfService: Boolean
    polarity: Polarity
    inactiveText: CharacterString
    activeText: CharacterString
    changeOfStateTime: DateTime
    changeOfStateCount: Unsigned
    timeOfStateCountReset: DateTime
    elapsedActiveTime: Unsigned
    timeOfActiveTimeReset: DateTime
    timeDelay: Unsigned
    notificationClass: Unsigned
    alarmValue: BinaryPV
    eventEnable: EventTransitionBits
    ackedTransitions: EventTransitionBits
    notifyType: NotifyType
    eventTimeStamps: ArrayOf(TimeStamp, _length=3)
    eventMessageTexts: ArrayOf(CharacterString, _length=3)
    eventMessageTextsConfig: ArrayOf(CharacterString, _length=3)
    eventDetectionEnable: Boolean
    eventAlgorithmInhibitRef: ObjectPropertyReference
    eventAlgorithmInhibit: Boolean
    timeDelayNormal: Unsigned
    reliabilityEvaluationInhibit: Boolean
    interfaceValue: OptionalBinaryPV

class BinaryLightingOutputObject(Object):
    _required = ...
    objectType = ...
    presentValue: BinaryLightingPV
    statusFlags: StatusFlags
    eventState: EventState
    reliability: Reliability
    outOfService: Boolean
    blinkWarnEnable: Boolean
    egressTime: Unsigned
    egressActive: Boolean
    feedbackValue: BinaryLightingPV
    priorityArray: ArrayOf(PriorityValue, _length=16)
    relinquishDefault: BinaryLightingPV
    power: Real
    polarity: Polarity
    elapsedActiveTime: Unsigned
    timeOfActiveTimeReset: DateTime
    strikeCount: Unsigned
    timeOfStrikeCountReset: DateTime
    eventDetectionEnable: Boolean
    notificationClass: Unsigned
    eventEnable: EventTransitionBits
    ackedTransitions: EventTransitionBits
    notifyType: NotifyType
    eventTimeStamps: ArrayOf(TimeStamp, _length=3)
    eventMessageTexts: ArrayOf(CharacterString, _length=3)
    eventMessageTextsConfig: ArrayOf(CharacterString, _length=3)
    reliabilityEvaluationInhibit: Boolean
    currentCommandPriority: OptionalUnsigned
    valueSource: ValueSource
    valueSourceArray: ArrayOf(ValueSource, _length=16)
    lastCommandTime: TimeStamp
    commandTimeArray: ArrayOf(TimeStamp, _length=16)
    auditPriorityFilter: OptionalPriorityFilter

class BinaryOutputObject(Object):
    _required = ...
    objectType = ...
    presentValue: BinaryPV
    deviceType: CharacterString
    statusFlags: StatusFlags
    eventState: EventState
    reliability: Reliability
    outOfService: Boolean
    polarity: Polarity
    inactiveText: CharacterString
    activeText: CharacterString
    changeOfStateTime: DateTime
    changeOfStateCount: Unsigned
    timeOfStateCountReset: DateTime
    elapsedActiveTime: Unsigned
    timeOfActiveTimeReset: DateTime
    minimumOffTime: Unsigned
    minimumOnTime: Unsigned
    priorityArray: ArrayOf(PriorityValue, _length=16)
    relinquishDefault: BinaryPV
    timeDelay: Unsigned
    notificationClass: Unsigned
    feedbackValue: BinaryPV
    eventEnable: EventTransitionBits
    ackedTransitions: EventTransitionBits
    notifyType: NotifyType
    eventTimeStamps: ArrayOf(TimeStamp, _length=3)
    eventMessageTexts: ArrayOf(CharacterString, _length=3)
    eventMessageTextsConfig: ArrayOf(CharacterString, _length=3)
    eventDetectionEnable: Boolean
    eventAlgorithmInhibitRef: ObjectPropertyReference
    eventAlgorithmInhibit: Boolean
    timeDelayNormal: Unsigned
    reliabilityEvaluationInhibit: Boolean
    interfaceValue: OptionalBinaryPV
    currentCommandPriority: OptionalUnsigned
    valueSource: ValueSource
    valueSourceArray: ArrayOf(ValueSource, _length=16)
    lastCommandTime: TimeStamp
    commandTimeArray: ArrayOf(TimeStamp, _length=16)
    auditPriorityFilter: OptionalPriorityFilter

class BinaryValueObject(Object):
    _required = ...
    objectType = ...
    presentValue: BinaryPV
    statusFlags: StatusFlags
    eventState: EventState
    reliability: Reliability
    outOfService: Boolean
    inactiveText: CharacterString
    activeText: CharacterString
    changeOfStateTime: DateTime
    changeOfStateCount: Unsigned
    timeOfStateCountReset: DateTime
    elapsedActiveTime: Unsigned
    timeOfActiveTimeReset: DateTime
    minimumOffTime: Unsigned
    minimumOnTime: Unsigned
    priorityArray: ArrayOf(PriorityValue, _length=16)
    relinquishDefault: BinaryPV
    timeDelay: Unsigned
    notificationClass: Unsigned
    alarmValue: BinaryPV
    eventEnable: EventTransitionBits
    ackedTransitions: EventTransitionBits
    notifyType: NotifyType
    eventTimeStamps: ArrayOf(TimeStamp, _length=3)
    eventMessageTexts: ArrayOf(CharacterString, _length=3)
    eventMessageTextsConfig: ArrayOf(CharacterString, _length=3)
    eventDetectionEnable: Boolean
    eventAlgorithmInhibitRef: ObjectPropertyReference
    eventAlgorithmInhibit: Boolean
    timeDelayNormal: Unsigned
    reliabilityEvaluationInhibit: Boolean
    currentCommandPriority: OptionalUnsigned
    valueSource: ValueSource
    valueSourceArray: ArrayOf(ValueSource, _length=16)
    lastCommandTime: TimeStamp
    commandTimeArray: ArrayOf(TimeStamp, _length=16)
    auditPriorityFilter: OptionalPriorityFilter

class BitStringValueObject(Object):
    _required = ...
    objectType = ...
    presentValue: BitString
    bitText: ArrayOf(CharacterString)
    statusFlags: StatusFlags
    eventState: EventState
    reliability: Reliability
    outOfService: Boolean
    priorityArray: ArrayOf(PriorityValue, _length=16)
    relinquishDefault: BitString
    timeDelay: Unsigned
    notificationClass: Unsigned
    alarmValues: ArrayOf(BitString)
    bitMask: BitString
    eventEnable: EventTransitionBits
    ackedTransitions: EventTransitionBits
    notifyType: NotifyType
    eventTimeStamps: ArrayOf(TimeStamp, _length=3)
    eventMessageTexts: ArrayOf(CharacterString, _length=3)
    eventMessageTextsConfig: ArrayOf(CharacterString, _length=3)
    eventDetectionEnable: Boolean
    eventAlgorithmInhibitRef: ObjectPropertyReference
    eventAlgorithmInhibit: Boolean
    timeDelayNormal: Unsigned
    reliabilityEvaluationInhibit: Boolean
    currentCommandPriority: OptionalUnsigned
    valueSource: ValueSource
    valueSourceArray: ArrayOf(ValueSource, _length=16)
    lastCommandTime: TimeStamp
    commandTimeArray: ArrayOf(TimeStamp, _length=16)
    auditPriorityFilter: OptionalPriorityFilter

class CalendarObject(Object):
    _required = ...
    objectType = ...
    presentValue: Boolean
    dateList: ListOf(CalendarEntry)

class ChannelObject(Object):
    _required = ...
    objectType = ...
    presentValue: ChannelValue
    lastPriority: Unsigned
    writeStatus: WriteStatus
    statusFlags: StatusFlags
    reliability: Reliability
    outOfService: Boolean
    listOfObjectPropertyReferences: ArrayOf(DeviceObjectPropertyReference)
    executionDelay: ArrayOf(Unsigned)
    allowGroupDelayInhibit: Boolean
    channelNumber: Unsigned
    controlGroups: ArrayOf(Unsigned)
    eventDetectionEnable: Boolean
    notificationClass: Unsigned
    eventEnable: EventTransitionBits
    eventState: EventState
    ackedTransitions: EventTransitionBits
    notifyType: NotifyType
    eventTimeStamps: ArrayOf(TimeStamp, _length=3)
    eventMessageTexts: ArrayOf(CharacterString, _length=3)
    eventMessageTextsConfig: ArrayOf(CharacterString, _length=3)
    reliabilityEvaluationInhibit: Boolean
    valueSource: ValueSource
    auditPriorityFilter: OptionalPriorityFilter

class CharacterStringValueObject(Object):
    _required = ...
    objectType = ...
    presentValue: CharacterString
    statusFlags: StatusFlags
    eventState: EventState
    reliability: Reliability
    outOfService: Boolean
    priorityArray: ArrayOf(PriorityValue, _length=16)
    relinquishDefault: CharacterString
    timeDelay: Unsigned
    notificationClass: Unsigned
    alarmValues: ArrayOf(OptionalCharacterString)
    faultValues: ArrayOf(OptionalCharacterString)
    eventEnable: EventTransitionBits
    ackedTransitions: EventTransitionBits
    notifyType: NotifyType
    eventTimeStamps: ArrayOf(TimeStamp, _length=3)
    eventMessageTexts: ArrayOf(CharacterString, _length=3)
    eventMessageTextsConfig: ArrayOf(CharacterString, _length=3)
    eventDetectionEnable: Boolean
    eventAlgorithmInhibitRef: ObjectPropertyReference
    eventAlgorithmInhibit: Boolean
    timeDelayNormal: Unsigned
    reliabilityEvaluationInhibit: Boolean
    currentCommandPriority: OptionalUnsigned
    valueSource: ValueSource
    valueSourceArray: ArrayOf(ValueSource, _length=16)
    lastCommandTime: TimeStamp
    commandTimeArray: ArrayOf(TimeStamp, _length=16)
    auditPriorityFilter: OptionalPriorityFilter

class CommandObject(Object):
    _required = ...
    objectType = ...
    presentValue: Unsigned
    inProcess: Boolean
    allWritesSuccessful: Boolean
    action: ArrayOf(ActionList)
    actionText: ArrayOf(CharacterString)
    statusFlags: StatusFlags
    eventState: EventState
    reliability: Reliability
    eventDetectionEnable: Boolean
    notificationClass: Unsigned
    eventEnable: EventTransitionBits
    ackedTransitions: EventTransitionBits
    notifyType: NotifyType
    eventTimeStamps: ArrayOf(TimeStamp, _length=3)
    eventMessageTexts: ArrayOf(CharacterString, _length=3)
    eventMessageTextsConfig: ArrayOf(CharacterString, _length=3)
    reliabilityEvaluationInhibit: Boolean
    valueSource: ValueSource

class CredentialDataInputObject(Object):
    _required = ...
    objectType = ...
    presentValue: AuthenticationFactor
    statusFlags: StatusFlags
    reliability: Reliability
    outOfService: Boolean
    supportedFormats: ArrayOf(AuthenticationFactorFormat)
    supportedFormatClasses: ArrayOf(Unsigned)
    updateTime: TimeStamp
    eventDetectionEnable: Boolean
    notificationClass: Unsigned
    eventEnable: EventTransitionBits
    eventState: EventState
    ackedTransitions: EventTransitionBits
    notifyType: NotifyType
    eventTimeStamps: ArrayOf(TimeStamp, _length=3)
    eventMessageTexts: ArrayOf(CharacterString, _length=3)
    eventMessageTextsConfig: ArrayOf(CharacterString, _length=3)
    reliabilityEvaluationInhibit: Boolean

class DatePatternValueObject(Object):
    _required = ...
    objectType = ...
    presentValue: Date
    statusFlags: StatusFlags
    eventState: EventState
    reliability: Reliability
    outOfService: Boolean
    priorityArray: ArrayOf(PriorityValue, _length=16)
    relinquishDefault: Date
    reliabilityEvaluationInhibit: Boolean
    eventDetectionEnable: Boolean
    notificationClass: Unsigned
    eventEnable: EventTransitionBits
    ackedTransitions: EventTransitionBits
    notifyType: NotifyType
    eventTimeStamps: ArrayOf(TimeStamp, _length=3)
    eventMessageTexts: ArrayOf(CharacterString, _length=3)
    eventMessageTextsConfig: ArrayOf(CharacterString, _length=3)
    currentCommandPriority: OptionalUnsigned
    valueSource: ValueSource
    valueSourceArray: ArrayOf(ValueSource, _length=16)
    lastCommandTime: TimeStamp
    commandTimeArray: ArrayOf(TimeStamp, _length=16)
    auditPriorityFilter: OptionalPriorityFilter

class DateTimePatternValueObject(Object):
    _required = ...
    objectType = ...
    presentValue: DateTime
    statusFlags: StatusFlags
    eventState: EventState
    reliability: Reliability
    outOfService: Boolean
    isUTC: Boolean
    priorityArray: ArrayOf(PriorityValue, _length=16)
    relinquishDefault: DateTime
    reliabilityEvaluationInhibit: Boolean
    eventDetectionEnable: Boolean
    notificationClass: Unsigned
    eventEnable: EventTransitionBits
    ackedTransitions: EventTransitionBits
    notifyType: NotifyType
    eventTimeStamps: ArrayOf(TimeStamp, _length=3)
    eventMessageTexts: ArrayOf(CharacterString, _length=3)
    eventMessageTextsConfig: ArrayOf(CharacterString, _length=3)
    currentCommandPriority: OptionalUnsigned
    valueSource: ValueSource
    valueSourceArray: ArrayOf(ValueSource, _length=16)
    lastCommandTime: TimeStamp
    commandTimeArray: ArrayOf(TimeStamp, _length=16)
    auditPriorityFilter: OptionalPriorityFilter

class DateTimeValueObject(Object):
    _required = ...
    objectType = ...
    presentValue: DateTime
    statusFlags: StatusFlags
    eventState: EventState
    reliability: Reliability
    outOfService: Boolean
    priorityArray: ArrayOf(PriorityValue, _length=16)
    relinquishDefault: DateTime
    isUTC: Boolean
    reliabilityEvaluationInhibit: Boolean
    eventDetectionEnable: Boolean
    notificationClass: Unsigned
    eventEnable: EventTransitionBits
    ackedTransitions: EventTransitionBits
    notifyType: NotifyType
    eventTimeStamps: ArrayOf(TimeStamp, _length=3)
    eventMessageTexts: ArrayOf(CharacterString, _length=3)
    eventMessageTextsConfig: ArrayOf(CharacterString, _length=3)
    currentCommandPriority: OptionalUnsigned
    valueSource: ValueSource
    valueSourceArray: ArrayOf(ValueSource, _length=16)
    lastCommandTime: TimeStamp
    commandTimeArray: ArrayOf(TimeStamp, _length=16)
    auditPriorityFilter: OptionalPriorityFilter

class DateValueObject(Object):
    _required = ...
    objectType = ...
    presentValue: Date
    statusFlags: StatusFlags
    eventState: EventState
    reliability: Reliability
    outOfService: Boolean
    priorityArray: ArrayOf(PriorityValue, _length=16)
    relinquishDefault: Date
    reliabilityEvaluationInhibit: Boolean
    eventDetectionEnable: Boolean
    notificationClass: Unsigned
    eventEnable: EventTransitionBits
    ackedTransitions: EventTransitionBits
    notifyType: NotifyType
    eventTimeStamps: ArrayOf(TimeStamp, _length=3)
    eventMessageTexts: ArrayOf(CharacterString, _length=3)
    eventMessageTextsConfig: ArrayOf(CharacterString, _length=3)
    currentCommandPriority: OptionalUnsigned
    valueSource: ValueSource
    valueSourceArray: ArrayOf(ValueSource, _length=16)
    lastCommandTime: TimeStamp
    commandTimeArray: ArrayOf(TimeStamp, _length=16)
    auditPriorityFilter: OptionalPriorityFilter

class DeviceObject(Object):
    _required = ...
    objectType = ...
    systemStatus: DeviceStatus
    vendorName: CharacterString
    vendorIdentifier: Unsigned
    modelName: CharacterString
    firmwareRevision: CharacterString
    applicationSoftwareVersion: CharacterString
    location: CharacterString
    protocolVersion: Unsigned
    protocolRevision: Unsigned
    protocolServicesSupported: ServicesSupported
    protocolObjectTypesSupported: ObjectTypesSupported
    objectList: ArrayOf(ObjectIdentifier)
    structuredObjectList: ArrayOf(ObjectIdentifier)
    maxApduLengthAccepted: Unsigned
    segmentationSupported: Segmentation
    maxSegmentsAccepted: Unsigned
    vtClassesSupported: ListOf(VTClass)
    activeVtSessions: ListOf(VTSession)
    localTime: Time
    localDate: Date
    utcOffset: Integer
    daylightSavingsStatus: Boolean
    apduSegmentTimeout: Unsigned
    apduTimeout: Unsigned
    numberOfApduRetries: Unsigned
    listOfSessionKeys: ListOf(SessionKey)
    timeSynchronizationRecipients: ListOf(Recipient)
    maxMaster: Unsigned
    maxInfoFrames: Unsigned
    deviceAddressBinding: ListOf(AddressBinding)
    databaseRevision: Unsigned
    configurationFiles: ArrayOf(ObjectIdentifier)
    lastRestoreTime: TimeStamp
    backupFailureTimeout: Unsigned
    activeCovSubscriptions: ListOf(COVSubscription)
    lastRestartReason: RestartReason
    timeOfDeviceRestart: TimeStamp
    restartNotificationRecipients: ListOf(Recipient)
    utcTimeSynchronizationRecipients: ListOf(Recipient)
    timeSynchronizationInterval: Unsigned
    alignIntervals: Boolean
    intervalOffset: Unsigned
    backupPreparationTime: Unsigned
    restorePreparationTime: Unsigned
    restoreCompletionTime: Unsigned
    backupAndRestoreState: BackupState
    serialNumber: CharacterString
    statusFlags: StatusFlags
    eventState: EventState
    reliability: Reliability
    eventDetectionEnable: Boolean
    notificationClass: Unsigned
    eventEnable: EventTransitionBits
    ackedTransitions: EventTransitionBits
    notifyType: NotifyType
    eventTimeStamps: ArrayOf(TimeStamp, _length=3)
    eventMessageTexts: ArrayOf(CharacterString, _length=3)
    eventMessageTextsConfig: ArrayOf(CharacterString, _length=3)
    reliabilityEvaluationInhibit: Boolean
    activeCovMultipleSubscriptions: ListOf(COVMultipleSubscription)
    auditNotificationRecipient: Recipient
    auditLevel: AuditLevel
    auditableOperations: AuditOperationFlags
    deviceUUID: OctetString

class ElevatorGroupObject(Object):
    _required = ...
    objectType = ...
    machineRoomID: ObjectIdentifier
    groupID: Unsigned8
    groupMembers: ArrayOf(ObjectIdentifier)
    groupMode: LiftGroupMode
    landingCalls: ListOf(LandingCallStatus)
    landingCallControl: LandingCallStatus

class EscalatorObject(Object):
    _required = ...
    objectType = ...
    statusFlags: StatusFlags
    elevatorGroup: ObjectIdentifier
    groupID: Unsigned8
    installationID: Unsigned8
    powerMode: Boolean
    operationDirection: EscalatorOperationDirection
    escalatorMode: EscalatorMode
    energyMeter: Real
    energyMeterRef: DeviceObjectReference
    reliability: Reliability
    outOfService: Boolean
    faultSignals: ListOf(EscalatorFault)
    passengerAlarm: Boolean
    timeDelay: Unsigned
    timeDelayNormal: Unsigned
    eventDetectionEnable: Boolean
    notificationClass: Unsigned
    eventEnable: EventTransitionBits
    eventState: EventState
    ackedTransitions: EventTransitionBits
    notifyType: NotifyType
    eventTimeStamps: ArrayOf(TimeStamp, _length=3)
    eventMessageTexts: ArrayOf(CharacterString, _length=3)
    eventMessageTextsConfig: ArrayOf(CharacterString, _length=3)
    eventAlgorithmInhibit: Boolean
    eventAlgorithmInhibitRef: ObjectPropertyReference
    reliabilityEvaluationInhibit: Boolean

class EventEnrollmentObject(Object):
    _required = ...
    objectType = ...
    eventType: EventType
    notifyType: NotifyType
    eventParameters: EventParameter
    objectPropertyReference: DeviceObjectPropertyReference
    eventState: EventState
    eventEnable: EventTransitionBits
    ackedTransitions: EventTransitionBits
    notificationClass: Unsigned
    eventTimeStamps: ArrayOf(TimeStamp, _length=3)
    eventMessageTexts: ArrayOf(CharacterString, _length=3)
    eventMessageTextsConfig: ArrayOf(CharacterString, _length=3)
    eventDetectionEnable: Boolean
    eventAlgorithmInhibitRef: ObjectPropertyReference
    eventAlgorithmInhibit: Boolean
    timeDelayNormal: Unsigned
    statusFlags: StatusFlags
    reliability: Reliability
    faultType: FaultType
    faultParameters: FaultParameter
    reliabilityEvaluationInhibit: Boolean

class EventLogObject(Object):
    _required = ...
    objectType = ...
    statusFlags: StatusFlags
    eventState: EventState
    reliability: Reliability
    enable: Boolean
    startTime: DateTime
    stopTime: DateTime
    stopWhenFull: Boolean
    bufferSize: Unsigned
    logBuffer: ListOf(EventLogRecord)
    recordCount: Unsigned
    totalRecordCount: Unsigned
    notificationThreshold: Unsigned
    recordsSinceNotification: Unsigned
    lastNotifyRecord: Unsigned
    notificationClass: Unsigned
    eventEnable: EventTransitionBits
    ackedTransitions: EventTransitionBits
    notifyType: NotifyType
    eventTimeStamps: ArrayOf(TimeStamp, _length=3)
    eventMessageTexts: ArrayOf(CharacterString, _length=3)
    eventMessageTextsConfig: ArrayOf(CharacterString, _length=3)
    eventDetectionEnable: Boolean
    eventAlgorithmInhibitRef: ObjectPropertyReference
    eventAlgorithmInhibit: Boolean
    reliabilityEvaluationInhibit: Boolean

class FileObject(Object):
    _required = ...
    objectType = ...
    fileType: CharacterString
    fileSize: Unsigned
    modificationDate: DateTime
    archive: Boolean
    readOnly: Boolean
    fileAccessMethod: FileAccessMethod
    recordCount: Unsigned

class GlobalGroupObject(Object):
    _required = ...
    objectType = ...
    groupMembers: ArrayOf(DeviceObjectPropertyReference)
    groupMemberNames: ArrayOf(CharacterString)
    presentValue: ArrayOf(PropertyAccessResult)
    statusFlags: StatusFlags
    eventState: EventState
    memberStatusFlags: StatusFlags
    reliability: Reliability
    outOfService: Boolean
    updateInterval: Unsigned
    requestedUpdateInterval: Unsigned
    covResubscriptionInterval: Unsigned
    clientCovIncrement: ClientCOV
    timeDelay: Unsigned
    notificationClass: Unsigned
    eventEnable: EventTransitionBits
    ackedTransitions: EventTransitionBits
    notifyType: NotifyType
    eventTimeStamps: ArrayOf(TimeStamp, _length=3)
    eventMessageTexts: ArrayOf(CharacterString, _length=3)
    eventMessageTextsConfig: ArrayOf(CharacterString, _length=3)
    eventDetectionEnable: Boolean
    eventAlgorithmInhibitRef: ObjectPropertyReference
    eventAlgorithmInhibit: Boolean
    timeDelayNormal: Unsigned
    covuPeriod: Unsigned
    covuRecipients: ListOf(Recipient)
    reliabilityEvaluationInhibit: Boolean

class GroupObject(Object):
    _required = ...
    objectType = ...
    listOfGroupMembers: ListOf(ReadAccessSpecification)
    presentValue: ListOf(ReadAccessResult)

class IntegerValueObject(Object):
    _required = ...
    objectType = ...
    presentValue: Integer
    statusFlags: StatusFlags
    eventState: EventState
    reliability: Reliability
    outOfService: Boolean
    units: EngineeringUnits
    priorityArray: ArrayOf(PriorityValue, _length=16)
    relinquishDefault: Integer
    covIncrement: Unsigned
    timeDelay: Unsigned
    notificationClass: Unsigned
    highLimit: Integer
    lowLimit: Integer
    deadband: Unsigned
    limitEnable: LimitEnable
    eventEnable: EventTransitionBits
    ackedTransitions: EventTransitionBits
    notifyType: NotifyType
    eventTimeStamps: ArrayOf(TimeStamp, _length=3)
    eventMessageTexts: ArrayOf(CharacterString, _length=3)
    eventMessageTextsConfig: ArrayOf(CharacterString, _length=3)
    eventDetectionEnable: Boolean
    eventAlgorithmInhibitRef: ObjectPropertyReference
    eventAlgorithmInhibit: Boolean
    timeDelayNormal: Unsigned
    reliabilityEvaluationInhibit: Boolean
    minPresValue: Integer
    maxPresValue: Integer
    resolution: Integer
    faultHighLimit: Integer
    faultLowLimit: Integer
    currentCommandPriority: OptionalUnsigned
    valueSource: ValueSource
    valueSourceArray: ArrayOf(ValueSource, _length=16)
    lastCommandTime: TimeStamp
    commandTimeArray: ArrayOf(TimeStamp, _length=16)
    auditPriorityFilter: OptionalPriorityFilter

class LargeAnalogValueObject(Object):
    _required = ...
    objectType = ...
    presentValue: Double
    statusFlags: StatusFlags
    eventState: EventState
    reliability: Reliability
    outOfService: Boolean
    units: EngineeringUnits
    priorityArray: ArrayOf(PriorityValue, _length=16)
    relinquishDefault: Double
    covIncrement: Double
    timeDelay: Unsigned
    notificationClass: Unsigned
    highLimit: Double
    lowLimit: Double
    deadband: Double
    limitEnable: LimitEnable
    eventEnable: EventTransitionBits
    ackedTransitions: EventTransitionBits
    notifyType: NotifyType
    eventTimeStamps: ArrayOf(TimeStamp, _length=3)
    eventMessageTexts: ArrayOf(CharacterString, _length=3)
    eventMessageTextsConfig: ArrayOf(CharacterString, _length=3)
    eventDetectionEnable: Boolean
    eventAlgorithmInhibitRef: ObjectPropertyReference
    eventAlgorithmInhibit: Boolean
    timeDelayNormal: Unsigned
    reliabilityEvaluationInhibit: Boolean
    minPresValue: Double
    maxPresValue: Double
    resolution: Double
    faultHighLimit: Double
    faultLowLimit: Double
    currentCommandPriority: OptionalUnsigned
    valueSource: ValueSource
    valueSourceArray: ArrayOf(ValueSource, _length=16)
    lastCommandTime: TimeStamp
    commandTimeArray: ArrayOf(TimeStamp, _length=16)
    auditPriorityFilter: OptionalPriorityFilter

class LifeSafetyPointObject(Object):
    _required = ...
    objectType = ...
    presentValue: LifeSafetyState
    trackingValue: LifeSafetyState
    deviceType: CharacterString
    statusFlags: StatusFlags
    eventState: EventState
    reliability: Reliability
    outOfService: Boolean
    mode: LifeSafetyMode
    acceptedModes: ListOf(LifeSafetyMode)
    timeDelay: Unsigned
    notificationClass: Unsigned
    lifeSafetyAlarmValues: ListOf(LifeSafetyState)
    alarmValues: ListOf(LifeSafetyState)
    faultValues: ListOf(LifeSafetyState)
    eventEnable: EventTransitionBits
    ackedTransitions: EventTransitionBits
    notifyType: NotifyType
    eventTimeStamps: ArrayOf(TimeStamp, _length=3)
    eventMessageTexts: ArrayOf(CharacterString, _length=3)
    eventMessageTextsConfig: ArrayOf(CharacterString, _length=3)
    eventDetectionEnable: Boolean
    eventAlgorithmInhibitRef: ObjectPropertyReference
    eventAlgorithmInhibit: Boolean
    timeDelayNormal: Unsigned
    reliabilityEvaluationInhibit: Boolean
    silenced: SilencedState
    operationExpected: LifeSafetyOperation
    maintenanceRequired: Maintenance
    setting: Unsigned
    directReading: Real
    units: EngineeringUnits
    memberOf: ListOf(DeviceObjectReference)
    floorNumber: Unsigned8
    valueSource: ValueSource

class LifeSafetyZoneObject(Object):
    _required = ...
    objectType = ...
    presentValue: LifeSafetyState
    trackingValue: LifeSafetyState
    deviceType: CharacterString
    statusFlags: StatusFlags
    eventState: EventState
    reliability: Reliability
    outOfService: Boolean
    mode: LifeSafetyMode
    acceptedModes: ListOf(LifeSafetyMode)
    timeDelay: Unsigned
    notificationClass: Unsigned
    lifeSafetyAlarmValues: ListOf(LifeSafetyState)
    alarmValues: ListOf(LifeSafetyState)
    faultValues: ListOf(LifeSafetyState)
    eventEnable: EventTransitionBits
    ackedTransitions: EventTransitionBits
    notifyType: NotifyType
    eventTimeStamps: ArrayOf(TimeStamp, _length=3)
    eventMessageTexts: ArrayOf(CharacterString, _length=3)
    eventMessageTextsConfig: ArrayOf(CharacterString, _length=3)
    eventDetectionEnable: Boolean
    eventAlgorithmInhibitRef: ObjectPropertyReference
    eventAlgorithmInhibit: Boolean
    timeDelayNormal: Unsigned
    reliabilityEvaluationInhibit: Boolean
    silenced: SilencedState
    operationExpected: LifeSafetyOperation
    maintenanceRequired: Boolean
    zoneMembers: ListOf(DeviceObjectReference)
    memberOf: ListOf(DeviceObjectReference)
    floorNumber: Unsigned8
    valueSource: ValueSource

class LiftObject(Object):
    _required = ...
    objectType = ...
    trackingValue: Real
    statusFlags: StatusFlags
    elevatorGroup: ObjectIdentifier
    groupID: Unsigned8
    installationID: Unsigned8
    floorText: ArrayOf(CharacterString)
    carDoorText: ArrayOf(CharacterString)
    assignedLandingCalls: ArrayOf(AssignedLandingCalls)
    makingCarCall: ArrayOf(Unsigned8)
    registeredCarCall: ArrayOf(LiftCarCallList)
    carPosition: Unsigned8
    carMovingDirection: LiftCarDirection
    carAssignedDirection: LiftCarDirection
    carDoorStatus: ArrayOf(DoorStatus)
    carDoorCommand: ArrayOf(LiftCarDoorCommand)
    carDoorZone: Boolean
    carMode: LiftCarMode
    carLoad: Real
    carLoadUnits: EngineeringUnits
    nextStoppingFloor: Unsigned
    passengerAlarm: Boolean
    timeDelay: Unsigned
    timeDelayNormal: Unsigned
    energyMeter: Real
    energyMeterRef: DeviceObjectReference
    reliability: Reliability
    outOfService: Boolean
    carDriveStatus: LiftCarDriveStatus
    faultSignals: ListOf(LiftFault)
    landingDoorStatus: ArrayOf(LandingDoorStatus)
    higherDeck: ObjectIdentifier
    lowerDeck: ObjectIdentifier
    eventDetectionEnable: Boolean
    notificationClass: Unsigned
    eventEnable: EventTransitionBits
    eventState: EventState
    ackedTransitions: EventTransitionBits
    notifyType: NotifyType
    eventTimeStamps: ArrayOf(TimeStamp, _length=3)
    eventMessageTexts: ArrayOf(CharacterString, _length=3)
    eventMessageTextsConfig: ArrayOf(CharacterString, _length=3)
    eventAlgorithmInhibitRef: ObjectPropertyReference
    eventAlgorithmInhibit: Boolean
    reliabilityEvaluationInhibit: Boolean

class LightingOutputObject(Object):
    _required = ...
    objectType = ...
    presentValue: Real
    trackingValue: Real
    lightingCommand: LightingCommand
    inProgress: LightingInProgress
    statusFlags: StatusFlags
    reliability: Reliability
    outOfService: Boolean
    blinkWarnEnable: Boolean
    egressTime: Unsigned
    egressActive: Boolean
    defaultFadeTime: Unsigned
    defaultRampRate: Real
    defaultStepIncrement: Real
    transition: LightingTransition
    feedbackValue: Real
    priorityArray: ArrayOf(PriorityValue, _length=16)
    relinquishDefault: Real
    power: Real
    instantaneousPower: Real
    minActualValue: Real
    maxActualValue: Real
    lightingCommandDefaultPriority: Unsigned
    covIncrement: Real
    reliabilityEvaluationInhibit: Boolean
    currentCommandPriority: OptionalUnsigned
    valueSource: ValueSource
    valueSourceArray: ArrayOf(ValueSource, _length=16)
    lastCommandTime: TimeStamp
    commandTimeArray: ArrayOf(TimeStamp, _length=16)
    auditPriorityFilter: OptionalPriorityFilter

class LoadControlObject(Object):
    _required = ...
    objectType = ...
    presentValue: ShedState
    stateDescription: CharacterString
    statusFlags: StatusFlags
    eventState: EventState
    reliability: Reliability
    requestedShedLevel: ShedLevel
    startTime: DateTime
    shedDuration: Unsigned
    dutyWindow: Unsigned
    enable: Boolean
    fullDutyBaseline: Real
    expectedShedLevel: ShedLevel
    actualShedLevel: ShedLevel
    shedLevels: ArrayOf(Unsigned)
    shedLevelDescriptions: ArrayOf(CharacterString)
    notificationClass: Unsigned
    timeDelay: Unsigned
    eventEnable: EventTransitionBits
    ackedTransitions: EventTransitionBits
    notifyType: NotifyType
    eventTimeStamps: ArrayOf(TimeStamp, _length=3)
    eventMessageTexts: ArrayOf(CharacterString, _length=3)
    eventMessageTextsConfig: ArrayOf(CharacterString, _length=3)
    eventDetectionEnable: Boolean
    eventAlgorithmInhibitRef: ObjectPropertyReference
    eventAlgorithmInhibit: Boolean
    timeDelayNormal: Unsigned
    reliabilityEvaluationInhibit: Boolean
    valueSource: ValueSource

class LoopObject(Object):
    _required = ...
    objectType = ...
    presentValue: Real
    statusFlags: StatusFlags
    eventState: EventState
    reliability: Reliability
    outOfService: Boolean
    updateInterval: Unsigned
    outputUnits: EngineeringUnits
    manipulatedVariableReference: ObjectPropertyReference
    controlledVariableReference: ObjectPropertyReference
    controlledVariableValue: Real
    controlledVariableUnits: EngineeringUnits
    setpointReference: SetpointReference
    setpoint: Real
    action: Action
    proportionalConstant: Real
    proportionalConstantUnits: EngineeringUnits
    integralConstant: Real
    integralConstantUnits: EngineeringUnits
    derivativeConstant: Real
    derivativeConstantUnits: EngineeringUnits
    bias: Real
    maximumOutput: Real
    minimumOutput: Real
    priorityForWriting: Unsigned
    covIncrement: Real
    timeDelay: Unsigned
    notificationClass: Unsigned
    errorLimit: Real
    deadband: Real
    eventEnable: EventTransitionBits
    ackedTransitions: EventTransitionBits
    notifyType: NotifyType
    eventTimeStamps: ArrayOf(TimeStamp, _length=3)
    eventMessageTexts: ArrayOf(CharacterString, _length=3)
    eventMessageTextsConfig: ArrayOf(CharacterString, _length=3)
    eventDetectionEnable: Boolean
    eventAlgorithmInhibitRef: ObjectPropertyReference
    eventAlgorithmInhibit: Boolean
    timeDelayNormal: Unsigned
    reliabilityEvaluationInhibit: Boolean
    lowDiffLimit: OptionalReal

class MultiStateInputObject(Object):
    _required = ...
    objectType = ...
    presentValue: Unsigned
    deviceType: CharacterString
    statusFlags: StatusFlags
    eventState: EventState
    reliability: Reliability
    outOfService: Boolean
    numberOfStates: Unsigned
    stateText: ArrayOf(CharacterString)
    timeDelay: Unsigned
    notificationClass: Unsigned
    alarmValues: ListOf(Unsigned)
    faultValues: ListOf(Unsigned)
    eventEnable: EventTransitionBits
    ackedTransitions: EventTransitionBits
    notifyType: NotifyType
    eventTimeStamps: ArrayOf(TimeStamp, _length=3)
    eventMessageTexts: ArrayOf(CharacterString, _length=3)
    eventMessageTextsConfig: ArrayOf(CharacterString, _length=3)
    eventDetectionEnable: Boolean
    eventAlgorithmInhibitRef: ObjectPropertyReference
    eventAlgorithmInhibit: Boolean
    timeDelayNormal: Unsigned
    reliabilityEvaluationInhibit: Boolean
    interfaceValue: OptionalUnsigned

class MultiStateOutputObject(Object):
    _required = ...
    objectType = ...
    presentValue: Unsigned
    deviceType: CharacterString
    statusFlags: StatusFlags
    eventState: EventState
    reliability: Reliability
    outOfService: Boolean
    numberOfStates: Unsigned
    stateText: ArrayOf(CharacterString)
    priorityArray: ArrayOf(PriorityValue, _length=16)
    relinquishDefault: Unsigned
    timeDelay: Unsigned
    notificationClass: Unsigned
    feedbackValue: Unsigned
    eventEnable: EventTransitionBits
    ackedTransitions: EventTransitionBits
    notifyType: NotifyType
    eventTimeStamps: ArrayOf(TimeStamp, _length=3)
    eventMessageTexts: ArrayOf(CharacterString, _length=3)
    eventMessageTextsConfig: ArrayOf(CharacterString, _length=3)
    eventDetectionEnable: Boolean
    eventAlgorithmInhibitRef: ObjectPropertyReference
    eventAlgorithmInhibit: Boolean
    timeDelayNormal: Unsigned
    reliabilityEvaluationInhibit: Boolean
    interfaceValue: OptionalUnsigned
    currentCommandPriority: OptionalUnsigned
    valueSource: ValueSource
    valueSourceArray: ArrayOf(ValueSource, _length=16)
    lastCommandTime: TimeStamp
    commandTimeArray: ArrayOf(TimeStamp, _length=16)
    auditPriorityFilter: OptionalPriorityFilter

class MultiStateValueObject(Object):
    _required = ...
    objectType = ...
    presentValue: Unsigned
    statusFlags: StatusFlags
    eventState: EventState
    reliability: Reliability
    outOfService: Boolean
    numberOfStates: Unsigned
    stateText: ArrayOf(CharacterString)
    priorityArray: ArrayOf(PriorityValue, _length=16)
    relinquishDefault: Unsigned
    timeDelay: Unsigned
    notificationClass: Unsigned
    alarmValues: ListOf(Unsigned)
    faultValues: ListOf(Unsigned)
    eventEnable: EventTransitionBits
    ackedTransitions: EventTransitionBits
    notifyType: NotifyType
    eventTimeStamps: ArrayOf(TimeStamp, _length=3)
    eventMessageTexts: ArrayOf(CharacterString, _length=3)
    eventMessageTextsConfig: ArrayOf(CharacterString, _length=3)
    eventDetectionEnable: Boolean
    eventAlgorithmInhibitRef: ObjectPropertyReference
    eventAlgorithmInhibit: Boolean
    timeDelayNormal: Unsigned
    reliabilityEvaluationInhibit: Boolean
    currentCommandPriority: OptionalUnsigned
    valueSource: ValueSource
    valueSourceArray: ArrayOf(ValueSource, _length=16)
    lastCommandTime: TimeStamp
    commandTimeArray: ArrayOf(TimeStamp, _length=16)
    auditPriorityFilter: OptionalPriorityFilter

class NetworkPortObject(Object):
    _required = ...
    objectType = ...
    statusFlags: StatusFlags
    reliability: Reliability
    outOfService: Boolean
    networkType: NetworkType
    protocolLevel: ProtocolLevel
    referencePort: Unsigned
    networkNumber: Unsigned16
    networkNumberQuality: NetworkNumberQuality
    changesPending: Boolean
    command: NetworkPortCommand
    macAddress: MACAddress
    apduLength: Unsigned
    linkSpeed: Real
    linkSpeeds: ArrayOf(Real)
    linkSpeedAutonegotiate: Boolean
    networkInterfaceName: CharacterString
    bacnetIPMode: IPMode
    ipAddress: IPv4OctetString
    bacnetIPUDPPort: Unsigned16
    ipSubnetMask: IPv4OctetString
    ipDefaultGateway: IPv4OctetString
    bacnetIPMulticastAddress: IPv4OctetString
    ipDNSServer: ArrayOf(IPv4OctetString)
    ipDHCPEnable: Boolean
    ipDHCPLeaseTime: Unsigned
    ipDHCPLeaseTimeRemaining: Unsigned
    ipDHCPServer: IPv4OctetString
    bacnetIPNATTraversal: Boolean
    bacnetIPGlobalAddress: HostNPort
    bbmdBroadcastDistributionTable: ListOf(BDTEntry)
    bbmdAcceptFDRegistrations: Boolean
    bbmdForeignDeviceTable: ListOf(FDTEntry)
    fdBBMDAddress: HostNPort
    fdSubscriptionLifetime: Unsigned16
    bacnetIPv6Mode: IPMode
    ipv6Address: IPv6OctetString
    ipv6PrefixLength: Unsigned8
    bacnetIPv6UDPPort: Unsigned16
    ipv6DefaultGateway: IPv6OctetString
    bacnetIPv6MulticastAddress: IPv6OctetString
    ipv6DNSServer: ArrayOf(IPv6OctetString)
    ipv6AutoAddressingEnable: Boolean
    ipv6DHCPLeaseTime: Unsigned
    ipv6DHCPLeaseTimeRemaining: Unsigned
    ipv6DHCPServer: IPv6OctetString
    ipv6ZoneIndex: CharacterString
    maxMaster: Unsigned8
    maxInfoFrames: Unsigned8
    slaveProxyEnable: Boolean
    manualSlaveAddressBinding: ListOf(AddressBinding)
    autoSlaveDiscovery: Boolean
    slaveAddressBinding: ListOf(AddressBinding)
    virtualMACAddressTable: ListOf(VMACEntry)
    routingTable: ListOf(RouterEntry)
    eventDetectionEnable: Boolean
    notificationClass: Unsigned
    eventEnable: EventTransitionBits
    ackedTransitions: EventTransitionBits
    notifyType: NotifyType
    eventTimeStamps: ArrayOf(TimeStamp, _length=3)
    eventMessageTexts: ArrayOf(CharacterString, _length=3)
    eventMessageTextsConfig: ArrayOf(CharacterString, _length=3)
    eventState: EventState
    reliabilityEvaluationInhibit: Boolean

class NetworkSecurityObject(Object):
    objectType = ...
    baseDeviceSecurityPolicy: SecurityLevel
    networkAccessSecurityPolicies: ArrayOf(NetworkSecurityPolicy)
    securityTimeWindow: Unsigned
    packetReorderTime: Unsigned
    distributionKeyRevision: Unsigned
    keySets: ArrayOf(SecurityKeySet)
    lastKeyServer: AddressBinding
    securityPDUTimeout: Unsigned
    updateKeySetTimeout: Unsigned
    supportedSecurityAlgorithms: ListOf(Unsigned)
    doNotHide: Boolean

class NotificationClassObject(Object):
    _required = ...
    objectType = ...
    notificationClass: Unsigned
    priority: ArrayOf(Unsigned)
    ackRequired: EventTransitionBits
    recipientList: ListOf(Destination)
    statusFlags: StatusFlags
    eventState: EventState
    reliability: Reliability
    eventDetectionEnable: Boolean
    eventEnable: EventTransitionBits
    ackedTransitions: EventTransitionBits
    notifyType: NotifyType
    eventTimeStamps: ArrayOf(TimeStamp, _length=3)
    eventMessageTexts: ArrayOf(CharacterString, _length=3)
    eventMessageTextsConfig: ArrayOf(CharacterString, _length=3)
    reliabilityEvaluationInhibit: Boolean

class NotificationForwarderObject(Object):
    _required = ...
    objectType = ...
    statusFlags: StatusFlags
    reliability: Reliability
    outOfService: Boolean
    recipientList: ListOf(Destination)
    subscribedRecipients: ListOf(EventNotificationSubscription)
    processIdentifierFilter: ProcessIdSelection
    portFilter: ArrayOf(PortPermission)
    localForwardingOnly: Boolean
    reliabilityEvaluationInhibit: Boolean

class OctetStringValueObject(Object):
    _required = ...
    objectType = ...
    presentValue: OctetString
    statusFlags: StatusFlags
    eventState: EventState
    reliability: Reliability
    outOfService: Boolean
    priorityArray: ArrayOf(PriorityValue, _length=16)
    relinquishDefault: OctetString
    reliabilityEvaluationInhibit: Boolean
    currentCommandPriority: OptionalUnsigned
    valueSource: ValueSource
    valueSourceArray: ArrayOf(ValueSource, _length=16)
    lastCommandTime: TimeStamp
    commandTimeArray: ArrayOf(TimeStamp, _length=16)
    auditPriorityFilter: OptionalPriorityFilter

class PositiveIntegerValueObject(Object):
    _required = ...
    objectType = ...
    presentValue: Unsigned
    statusFlags: StatusFlags
    eventState: EventState
    reliability: Reliability
    outOfService: Boolean
    units: EngineeringUnits
    priorityArray: ArrayOf(PriorityValue, _length=16)
    relinquishDefault: Unsigned
    covIncrement: Unsigned
    timeDelay: Unsigned
    notificationClass: Unsigned
    highLimit: Unsigned
    lowLimit: Unsigned
    deadband: Unsigned
    limitEnable: LimitEnable
    eventEnable: EventTransitionBits
    ackedTransitions: EventTransitionBits
    notifyType: NotifyType
    eventTimeStamps: ArrayOf(TimeStamp, _length=3)
    eventMessageTexts: ArrayOf(CharacterString, _length=3)
    eventMessageTextsConfig: ArrayOf(CharacterString, _length=3)
    eventDetectionEnable: Boolean
    eventAlgorithmInhibitRef: ObjectPropertyReference
    eventAlgorithmInhibit: Boolean
    timeDelayNormal: Unsigned
    reliabilityEvaluationInhibit: Boolean
    minPresValue: Unsigned
    maxPresValue: Unsigned
    resolution: Unsigned
    faultHighLimit: Unsigned
    faultLowLimit: Unsigned
    currentCommandPriority: OptionalUnsigned
    valueSource: ValueSource
    valueSourceArray: ArrayOf(ValueSource, _length=16)
    lastCommandTime: TimeStamp
    commandTimeArray: ArrayOf(TimeStamp, _length=16)
    auditPriorityFilter: OptionalPriorityFilter

class ProgramObject(Object):
    _required = ...
    objectType = ...
    programState: ProgramState
    programChange: ProgramRequest
    reasonForHalt: ProgramError
    descriptionOfHalt: CharacterString
    programLocation: CharacterString
    instanceOf: CharacterString
    statusFlags: StatusFlags
    reliability: Reliability
    outOfService: Boolean
    eventDetectionEnable: Boolean
    notificationClass: Unsigned
    eventEnable: EventTransitionBits
    eventState: EventState
    ackedTransitions: EventTransitionBits
    notifyType: NotifyType
    eventTimeStamps: ArrayOf(TimeStamp, _length=3)
    eventMessageTexts: ArrayOf(CharacterString, _length=3)
    eventMessageTextsConfig: ArrayOf(CharacterString, _length=3)
    reliabilityEvaluationInhibit: Boolean

class PulseConverterObject(Object):
    _required = ...
    objectType = ...
    presentValue: Real
    inputReference: ObjectPropertyReference
    statusFlags: StatusFlags
    eventState: EventState
    reliability: Reliability
    outOfService: Boolean
    units: EngineeringUnits
    scaleFactor: Real
    adjustValue: Real
    count: Unsigned
    updateTime: DateTime
    countChangeTime: DateTime
    countBeforeChange: Unsigned
    covIncrement: Real
    covPeriod: Unsigned
    notificationClass: Unsigned
    timeDelay: Unsigned
    highLimit: Real
    lowLimit: Real
    deadband: Real
    limitEnable: LimitEnable
    eventEnable: EventTransitionBits
    ackedTransitions: EventTransitionBits
    notifyType: NotifyType
    eventTimeStamps: ArrayOf(TimeStamp, _length=3)
    eventMessageTexts: ArrayOf(CharacterString, _length=3)
    eventMessageTextsConfig: ArrayOf(CharacterString, _length=3)
    eventDetectionEnable: Boolean
    eventAlgorithmInhibitRef: ObjectPropertyReference
    eventAlgorithmInhibit: Boolean
    timeDelayNormal: Unsigned
    reliabilityEvaluationInhibit: Boolean

class ScheduleObject(Object):
    _required = ...
    objectType = ...
    presentValue: AnyAtomic
    effectivePeriod: DateRange
    weeklySchedule: ArrayOf(DailySchedule, _length=7)
    exceptionSchedule: ArrayOf(SpecialEvent)
    scheduleDefault: AnyAtomic
    listOfObjectPropertyReferences: ListOf(DeviceObjectPropertyReference)
    priorityForWriting: Unsigned
    statusFlags: StatusFlags
    reliability: Reliability
    outOfService: Boolean
    eventDetectionEnable: Boolean
    notificationClass: Unsigned
    eventEnable: EventTransitionBits
    eventState: EventState
    ackedTransitions: EventTransitionBits
    notifyType: NotifyType
    eventTimeStamps: ArrayOf(TimeStamp, _length=3)
    eventMessageTexts: ArrayOf(CharacterString, _length=3)
    eventMessageTextsConfig: ArrayOf(CharacterString, _length=3)
    reliabilityEvaluationInhibit: Boolean

class StagingObject(Object):
    _required = ...
    objectType = ...
    presentValue: Real
    presentStage: Unsigned
    stages: ArrayOf(StageLimitValue)
    stageNames: ArrayOf(CharacterString)
    statusFlags: StatusFlags
    eventState: EventState
    reliability: Reliability
    outOfService: Boolean
    units: EngineeringUnits
    targetReferences: ArrayOf(DeviceObjectReference)
    priorityForWriting: Unsigned
    defaultPresentValue: Real
    minPresValue: Real
    maxPresValue: Real
    covIncrement: Real
    notificationClass: Unsigned
    eventEnable: EventTransitionBits
    ackedTransitions: EventTransitionBits
    notifyType: NotifyType
    eventTimeStamps: ArrayOf(TimeStamp, _length=3)
    eventMessageTexts: ArrayOf(CharacterString, _length=3)
    eventMessageTextsConfig: ArrayOf(CharacterString, _length=3)
    eventDetectionEnable: Boolean
    reliabilityEvaluationInhibit: Boolean
    valueSource: ValueSource

class StructuredViewObject(Object):
    _required = ...
    objectType = ...
    nodeType: NodeType
    nodeSubtype: CharacterString
    subordinateList: ArrayOf(DeviceObjectReference)
    subordinateAnnotations: ArrayOf(CharacterString)
    subordinateTags: ArrayOf(NameValueCollection)
    subordinateNodeTypes: ArrayOf(NodeType)
    subordinateRelationships: ArrayOf(Relationship)
    defaultSubordinateRelationship: Relationship
    represents: DeviceObjectReference

class TimePatternValueObject(Object):
    _required = ...
    objectType = ...
    presentValue: Time
    statusFlags: StatusFlags
    eventState: EventState
    reliability: Reliability
    outOfService: Boolean
    priorityArray: ArrayOf(PriorityValue, _length=16)
    relinquishDefault: Time
    reliabilityEvaluationInhibit: Boolean
    eventDetectionEnable: Boolean
    notificationClass: Unsigned
    eventEnable: EventTransitionBits
    ackedTransitions: EventTransitionBits
    notifyType: NotifyType
    eventTimeStamps: ArrayOf(TimeStamp, _length=3)
    eventMessageTexts: ArrayOf(CharacterString, _length=3)
    eventMessageTextsConfig: ArrayOf(CharacterString, _length=3)
    currentCommandPriority: OptionalUnsigned
    valueSource: ValueSource
    valueSourceArray: ArrayOf(ValueSource, _length=16)
    lastCommandTime: TimeStamp
    commandTimeArray: ArrayOf(TimeStamp, _length=16)
    auditPriorityFilter: OptionalPriorityFilter

class TimeValueObject(Object):
    _required = ...
    objectType = ...
    presentValue: Time
    statusFlags: StatusFlags
    eventState: EventState
    reliability: Reliability
    outOfService: Boolean
    priorityArray: ArrayOf(PriorityValue, _length=16)
    relinquishDefault: Time
    reliabilityEvaluationInhibit: Boolean
    eventDetectionEnable: Boolean
    notificationClass: Unsigned
    eventEnable: EventTransitionBits
    ackedTransitions: EventTransitionBits
    notifyType: NotifyType
    eventTimeStamps: ArrayOf(TimeStamp, _length=3)
    eventMessageTexts: ArrayOf(CharacterString, _length=3)
    eventMessageTextsConfig: ArrayOf(CharacterString, _length=3)
    currentCommandPriority: OptionalUnsigned
    valueSource: ValueSource
    valueSourceArray: ArrayOf(ValueSource, _length=16)
    lastCommandTime: TimeStamp
    commandTimeArray: ArrayOf(TimeStamp, _length=16)
    auditPriorityFilter: OptionalPriorityFilter

class TimerObject(Object):
    _required = ...
    objectType = ...
    presentValue: Unsigned
    statusFlags: StatusFlags
    eventState: EventState
    reliability: Reliability
    outOfService: Boolean
    timerState: TimerState
    timerRunning: Boolean
    updateTime: DateTime
    lastStateChange: TimerTransition
    expirationTime: DateTime
    initialTimeout: Unsigned
    defaultTimeout: Unsigned
    minPresValue: Unsigned
    maxPresValue: Unsigned
    resolution: Unsigned
    stateChangeValues: ArrayOf(TimerStateChangeValue, _length=7)
    listOfObjectPropertyReferences: ListOf(DeviceObjectPropertyReference)
    priorityForWriting: Unsigned
    eventDetectionEnable: Boolean
    notificationClass: Unsigned
    timeDelay: Unsigned
    timeDelayNormal: Unsigned
    alarmValues: ListOf(TimerState)
    eventEnable: EventTransitionBits
    ackedTransitions: EventTransitionBits
    notifyType: NotifyType
    eventTimeStamps: ArrayOf(TimeStamp, _length=3)
    eventMessageTexts: ArrayOf(CharacterString, _length=3)
    eventMessageTextsConfig: ArrayOf(CharacterString, _length=3)
    eventAlgorithmInhibitRef: ObjectPropertyReference
    eventAlgorithmInhibit: Boolean
    reliabilityEvaluationInhibit: Boolean

class TrendLogMultipleObject(Object):
    _required = ...
    objectType = ...
    statusFlags: StatusFlags
    eventState: EventState
    reliability: Reliability
    enable: Boolean
    startTime: DateTime
    stopTime: DateTime
    logDeviceObjectProperty: ArrayOf(DeviceObjectPropertyReference)
    loggingType: LoggingType
    logInterval: Unsigned
    alignIntervals: Boolean
    intervalOffset: Unsigned
    trigger: Boolean
    stopWhenFull: Boolean
    bufferSize: Unsigned
    logBuffer: ListOf(LogMultipleRecord)
    recordCount: Unsigned
    totalRecordCount: Unsigned
    notificationThreshold: Unsigned
    recordsSinceNotification: Unsigned
    lastNotifyRecord: Unsigned
    notificationClass: Unsigned
    eventEnable: EventTransitionBits
    ackedTransitions: EventTransitionBits
    notifyType: NotifyType
    eventTimeStamps: ArrayOf(TimeStamp, _length=3)
    eventMessageTexts: ArrayOf(CharacterString, _length=3)
    eventMessageTextsConfig: ArrayOf(CharacterString, _length=3)
    eventDetectionEnable: Boolean
    eventAlgorithmInhibitRef: ObjectPropertyReference
    eventAlgorithmInhibit: Boolean
    reliabilityEvaluationInhibit: Boolean

class TrendLogObject(Object):
    _required = ...
    objectType = ...
    statusFlags: StatusFlags
    eventState: EventState
    reliability: Reliability
    enable: Boolean
    startTime: DateTime
    stopTime: DateTime
    logDeviceObjectProperty: DeviceObjectPropertyReference
    logInterval: Unsigned
    covResubscriptionInterval: Unsigned
    clientCovIncrement: ClientCOV
    stopWhenFull: Boolean
    bufferSize: Unsigned
    logBuffer: ListOf(LogRecord)
    recordCount: Unsigned
    totalRecordCount: Unsigned
    loggingType: LoggingType
    alignIntervals: Boolean
    intervalOffset: Unsigned
    trigger: Boolean
    notificationThreshold: Unsigned
    recordsSinceNotification: Unsigned
    lastNotifyRecord: Unsigned
    notificationClass: Unsigned
    eventEnable: EventTransitionBits
    ackedTransitions: EventTransitionBits
    notifyType: NotifyType
    eventTimeStamps: ArrayOf(TimeStamp, _length=3)
    eventMessageTexts: ArrayOf(CharacterString, _length=3)
    eventMessageTextsConfig: ArrayOf(CharacterString, _length=3)
    eventDetectionEnable: Boolean
    eventAlgorithmInhibitRef: ObjectPropertyReference
    eventAlgorithmInhibit: Boolean
    reliabilityEvaluationInhibit: Boolean
