"""
This type stub file was generated by pyright.
"""

from typing import Any, Dict

"""
Settings
"""
class Settings(Dict[str, Any]):
    """
    Settings
    """
    def __getattr__(self, name: str) -> Any:
        ...
    
    def __setattr__(self, name: str, value: Any) -> None:
        ...
    


settings = ...
def os_settings() -> None:
    """
    Update the settings from known OS environment variables.
    """
    ...

def dict_settings(**kwargs: Any) -> None:
    """
    Update the settings from key/value content.  Lists are morphed into sets
    if necessary, giving a setting any value is acceptable if there isn't one
    already set, otherwise protect against setting type changes.
    """
    ...

