"""
This type stub file was generated by pyright.
"""

from typing import Callable
from ..debugging import bacpypes_debugging
from ..object import (
    BinaryInputObject as _BinaryInputObject,
    BinaryOutputObject as _BinaryOutputObject,
    BinaryValueObject as _BinaryValueObject,
)
from .object import Object as _Object
from .cov import GenericCriteria
from .cmd import Commandable
from .event import ChangeOfStateEventAlgorithm, CommandFailureEventAlgorithm

"""
Binary Input, Output, and Value Object
"""
_debug = ...
_log = ...
_vendor_id = ...

class BinaryInputObject(_Object, _BinaryInputObject):
    """
    A local binary input object.
    """

    _debug: Callable[..., None]
    _cov_criteria = GenericCriteria
    _required = ...

class BinaryInputObjectIR(BinaryInputObject):
    """
    A local binary input object with intrinsic reporting.
    """

    _debug: Callable[..., None]
    _event_algorithm: ChangeOfStateEventAlgorithm
    _required = ...
    _optional = ...
    def __init__(self, **kwargs) -> None: ...

class BinaryOutputObject(Commandable, _Object, _BinaryOutputObject):
    """
    A local binary output object.
    """

    _debug: Callable[..., None]
    _cov_criteria = GenericCriteria
    _required = ...

class BinaryOutputObjectIR(BinaryOutputObject):
    """
    A local binary output object with intrinsic reporting.
    """

    _debug: Callable[..., None]
    _event_algorithm: CommandFailureEventAlgorithm
    _required = ...
    _optional = ...
    def __init__(self, **kwargs) -> None: ...

class BinaryValueObject(_Object, _BinaryValueObject):
    """
    Vanilla Binary Value Object
    """

    _debug: Callable[..., None]
    _cov_criteria = GenericCriteria
    _required = ...

class BinaryValueObjectCmd(Commandable, _BinaryValueObject):
    """
    Commandable Binary Value Object
    """

    _required = ...

class BinaryValueObjectIR(BinaryValueObjectCmd):
    """
    Commandable Binary Value Object with Intrinsic Reporting
    """

    _debug: Callable[..., None]
    _event_algorithm: ChangeOfStateEventAlgorithm
    _required = ...
    _optional = ...
    def __init__(self, **kwargs) -> None: ...
