"""
This type stub file was generated by pyright.
"""

from typing import Any, Callable
from ..debugging import bacpypes_debugging
from ..primitivedata import Date, Time
from ..basetypes import ListOfCOVSubscription, ObjectTypesSupported, ServicesSupported
from ..object import DeviceObject as _DeviceObject
from .object import Object

"""
Device Object
"""
_debug = ...
_log = ...
_vendor_id = ...
ArrayOfObjectIdentifier = ...
ListOfAddressBinding = ...
@bacpypes_debugging
class DeviceObject(Object, _DeviceObject):
    """
    A local device object has a dynamically generated localDate, localTime, and
    objectList property.
    """
    _debug: Callable[..., None]
    objectType = ...
    systemStatus = ...
    vendorName = ...
    vendorIdentifier = ...
    modelName = ...
    firmwareRevision = ...
    applicationSoftwareVersion = ...
    protocolVersion = ...
    protocolRevision = ...
    databaseRevision = ...
    maxApduLengthAccepted = ...
    segmentationSupported = ...
    maxSegmentsAccepted = ...
    apduSegmentTimeout = ...
    apduTimeout = ...
    numberOfApduRetries = ...
    @property
    def localDate(self) -> Date:
        """Return the local date."""
        ...
    
    @localDate.setter
    def localDate(self, value: Any) -> None:
        """Change the local date, ignored."""
        ...
    
    @property
    def localTime(self) -> Time:
        """Return the local time."""
        ...
    
    @localTime.setter
    def localTime(self, value: Any) -> None:
        """Change the local time, ignored."""
        ...
    
    @property
    def objectList(self) -> ArrayOfObjectIdentifier:
        """
        Return the list of identifiers for the objects in the application.  If
        this object isn't bound to an application, return a list of just itself.
        """
        ...
    
    @objectList.setter
    def objectList(self, value: Any) -> None:
        """Change the list of objects in the application, ignored."""
        ...
    
    @property
    def protocolServicesSupported(self) -> ServicesSupported:
        """Return the protocol services supported."""
        ...
    
    @protocolServicesSupported.setter
    def protocolServicesSupported(self, value: Any) -> None:
        """Change the protocol services supported, ignored."""
        ...
    
    @property
    def protocolObjectTypesSupported(self) -> ObjectTypesSupported:
        """Return the protocol object types supported."""
        ...
    
    @protocolObjectTypesSupported.setter
    def protocolObjectTypesSupported(self, value: Any) -> None:
        """Change the protocol object types supported, ignored."""
        ...
    
    @property
    def deviceAddressBinding(self) -> ListOfAddressBinding:
        """Return the device address binding list."""
        ...
    
    @deviceAddressBinding.setter
    def deviceAddressBinding(self, value: Any) -> None:
        """Change the device address binding list, ignored."""
        ...
    
    @property
    def activeCovSubscriptions(self) -> ListOfCOVSubscription:
        """Return the list of active subscriptions."""
        ...
    
    @activeCovSubscriptions.setter
    def activeCovSubscriptions(self, value: Any) -> None:
        """Change the active subscriptions."""
        ...
    


