"""
This type stub file was generated by pyright.
"""

from typing import Callable, Optional
from ..debugging import bacpypes_debugging
from ..pdu import Address
from ..primitivedata import CharacterString
from ..object import NetworkPortObject as _NetworkPortObject
from .object import Object as _Object

"""
Network Port Object
"""
_debug = ...
_log = ...
_vendor_id = ...

class NetworkPortObject(_Object, _NetworkPortObject):
    """
    A local network port object.
    """

    _debug: Callable[..., None]
    objectType = ...
    def __init__(
        self, addr: Optional[Address, CharacterString] = ..., *args, **kwargs
    ) -> None: ...
    @property
    def address(self) -> Address:
        """
        Interpret the contents returning an Address that has all the
        tuples necessary for sockets.
        """
        ...
